### ISSUE TITLE
wrapper script issues

### ISSUE THREAD

**Issue by roland-github** [cagdasbas/ipa_notify#1]
Hi, 

installed the script but ipa-notify wrapper is failing (wrong main maybe, I'm not a python programmer).
Somehow works if module/script called directly.
Please check/see below out.
Are you aware of any other issues with freeipa 4.6? 
Our freeipa server is calling other servers which are connected to it when receiving an ipa query on API, but it could be also related to our older freeipa install/upgrades which might have some bad legacy freeipa configs.

> ipa-notify
Traceback (most recent call last):
  File "/usr/local/bin/ipa-notify", line 11, in <module>
    load_entry_point('ipa-notify==0.2.1', 'console_scripts', 'ipa-notify')()
TypeError: main() missing 3 required positional arguments: 'args', 'client', and 'notifier'

thank you

**Comment by cagdasbas** [comment]
Hi,

It was an obvious bug but strange enough it always works in my environment on different machines with different virtualenvs. Anyway it should be fixed in 0.2.2. Please write back if it's still an issue. 

I didn't encounter any issue on my IPA servers which are 4.6.6 on CentOS7.

**Comment by roland-github** [comment]
Thank you. Still have some issues.
Do you have freeipa multi-master setup?
When gathering account lock status it seems python-freeipa module query all masters and it is using only first value.
Also, krbLoginFailedCount is not replicated to all masters being treated only locally.
Could you consider a fix for this?
Let me know if you need another issue to be opened.

**Comment by roland-github** [comment]
python-freeipa:
 user_status(a_useruid, o_all=True, o_raw=False)
    Lockout status of a user account
This connects to each IPA master and displays the lockout status on each one.

code:
<------>if int(user_status['result']**[0]**['krbloginfailedcount']**[0]**) >= ....

**Comment by cagdasbas** [comment]
Okay first the wrapper script issue. what is your
OS/Distribution-version: ?
Python version: ?
Are you using virtualenv? how did you install the package with `--user` flag or did you install it globally?
Can you send `pip freeze` output of your environment?

Let me replicate your setup and see if I can find out the problem. I tried it on CentOS 7 and Fedora 33 with python 3.6 and 3.8. I tried with both virtualenv and without a virtualenv with `--user` flag. 

Yes I have three masters. I wasn't aware of the krbLoginFailedCount is not being replicated. It's an odd behavior. 
Let me look into it. What do you think, should I report each master lock status separately?

**Comment by roland-github** [comment]
Sorry for the confusion. I'll open another issue for the second issue.
Wrapper script issue is fixed, tested v0.2.2 today.
We are using CentOS7.9 with python3(.6) from CentOS base repo.
Script was installed globally.

**Comment by cagdasbas** [comment]
Great! Closing the issue.
