### ISSUE TITLE
User lock notification issue

### ISSUE THREAD

**Issue by roland-github** [cagdasbas/ipa_notify#2]
We have freeipa multi-master setup.
When gathering account lock status it seems python-freeipa module query all masters and it is using only first value, not the same with the queried server in our case, so our test cases failed.
python-freeipa(https://python-freeipa.readthedocs.io/en/latest/):
user_status(a_useruid, o_all=True, o_raw=False)
Lockout status of a user account
This connects to each IPA master and displays the lockout status on each one.
code:
<------>if int(user_status['result'][0]['krbloginfailedcount'][0]) >= ....
krbLoginFailedCount is not replicated to all masters being treated only locally on the master which was used when authentication failed.
Would be nice to have reports with login locks and associated freeipa master server name/fqdn since we need to unlock the user on that specific master.

**Comment by cagdasbas** [comment]
It should be fixed in v0.2.3.
