### ISSUE TITLE
just a suggestion/feature request about script run

### ISSUE THREAD

**Issue by roland-github** [cagdasbas/ipa_notify#3]
I have added an argument named "--no-expiry-check" and an if statement in main.py (on our local install) so we can disable script expiry checks on demand and allow to run only account lock checks
This is useful when you need to run account locks checks more often than 24h, that way notifying only admins about locked accounts and limiting notifications to user password expiry to 1/day by running two different cron jobs.

**Comment by roland-github** [comment]
noop is doing about the same thing but considering that script run takes about 8 minutes for 120 users disabling any additional request might help to reduce that

**Comment by cagdasbas** [comment]
Yes I have this in my mind for sometime. I'll implement in a couple of days. I'm planning to introduce two separate flags which will switch on/off each check. Can be used individually and together for checking everything.

**Comment by cagdasbas** [comment]
It's implemented in v0.3.3. Please reopen if you encounter a problem
