### ISSUE TITLE
Detailed instructions

### ISSUE THREAD

**Issue by epigraphe** [cagdasbas/ipa_notify#4]
Detailed instructions
Please tell us in more detail what needs to be done halfway through point 4.
What command should be executed in NOOP and how to do it?
What script should you create?
When and where to download files from the repository?

I beg your pardon for my stupidity, this is the first time I do this

**Comment by cagdasbas** [comment]
No problem dude, not stupidity at all. My instructions were incomplete because I assumed a fair amount of python knowledge. I'll update the readme when I got the chance.

**Comment by epigraphe** [comment]
Thank you very much. Sorry to cause inconvenience, but I really want to use your product for my FREEIPA

**Comment by cagdasbas** [comment]
Hi. Sorry, I was really busy. I've added more instructions about the installation. Please feel free to ask if you encounter any problems.
