### ISSUE TITLE
email security none is not working as expected

### ISSUE THREAD

**Issue by roland-github** [cagdasbas/ipa_notify#5]
Email security none is not working. It is trying to auth by user/pass.
None should be an option to use the host's local relay/local email service which do not require user/password.
Avoid below when security set to none:
```
                                smtp_conn.login(self.user, self.password)
                                logging.debug("smtp login successful")

```

**Comment by cagdasbas** [comment]
Sorry for the delay. Fixed in 0.3.12. Please feel free to open open it again.

**Comment by cagdasbas** [comment]
Btw, forgot to mention. Maybe the parameter name is a little deceiving but smtp-security=none means connecting without any encryption. If you don't want to login to the mail agent leave smtp-user and smtp-password empty (which is default on 0.3.13).

**Comment by roland-github** [comment]
Hi,

yes, you are right too :)
I was trying to send notification emails based on local relay not user/pass authentication
I was not able to do that on older versions
Thanks for the update, I'll try it soon.
